apiVersion: v1
kind: List
metadata: {}
items:

- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: cassandra-pvc-1
  spec:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 500M

- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: cassandra-pvc-2
  spec:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 500M

- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: cassandra-pvc-3
  spec:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 500M

- apiVersion: v1
  kind: ReplicationController
  metadata:
    name: cassandra-1
    # The labels will be applied automatically
    # from the labels in the pod template, if not set
    # labels:
      # app: cassandra
  spec:
    replicas: 1
    # The selector will be applied automatically
    # from the labels in the pod template, if not set.
    # selector:
        # app: cassandra
    template:
      metadata:
        labels:
          app: cassandra
          node: cassandra-1
      spec:
        containers:
          - command:
              - /run.sh
            resources:
              limits:
                cpu: 0.4
                memory: 3Gi
              requests:
                cpu: 0.4
                memory: 3Gi
            env:
              - name: MAX_HEAP_SIZE
                value: 2G
              - name: HEAP_NEWSIZE
                value: 512M
              - name: POD_NAMESPACE
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.namespace
              - name: POD_IP
                valueFrom:
                  fieldRef:
                    fieldPath: status.podIP
            image: 172.30.1.1:5000/waus-bikeshedders/openshift-cassandra:latest
            name: cassandra-1
            ports:
              - containerPort: 9042
                name: cql
              - containerPort: 9160
                name: thrift
            volumeMounts:
              - mountPath: /cassandra_data
                name: cassandra-data
        volumes:
         - name: cassandra-data
           persistentVolumeClaim:
             claimName: cassandra-pvc-1

- apiVersion: v1
  kind: ReplicationController
  metadata:
    name: cassandra-2
    # The labels will be applied automatically
    # from the labels in the pod template, if not set
    # labels:
      # app: cassandra
  spec:
    replicas: 1
    # The selector will be applied automatically
    # from the labels in the pod template, if not set.
    # selector:
        # app: cassandra
    template:
      metadata:
        labels:
          app: cassandra
          node: cassandra-2
      spec:
        containers:
          - command:
              - /run.sh
            resources:
              limits:
                cpu: 0.4
                memory: 3Gi
              requests:
                cpu: 0.4
                memory: 3Gi
            env:
              - name: MAX_HEAP_SIZE
                value: 2G
              - name: HEAP_NEWSIZE
                value: 512M
              - name: POD_NAMESPACE
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.namespace
              - name: POD_IP
                valueFrom:
                  fieldRef:
                    fieldPath: status.podIP
            image: 172.30.1.1:5000/waus-bikeshedders/openshift-cassandra:latest
            name: cassandra-2
            ports:
              - containerPort: 9042
                name: cql
              - containerPort: 9160
                name: thrift
            volumeMounts:
              - mountPath: /cassandra_data
                name: cassandra-data
        volumes:
         - name: cassandra-data
           persistentVolumeClaim:
             claimName: cassandra-pvc-2

- apiVersion: v1
  kind: ReplicationController
  metadata:
    name: cassandra-3
    # The labels will be applied automatically
    # from the labels in the pod template, if not set
    # labels:
      # app: cassandra
  spec:
    replicas: 1
    # The selector will be applied automatically
    # from the labels in the pod template, if not set.
    # selector:
        # app: cassandra
    template:
      metadata:
        labels:
          app: cassandra
          node: cassandra-3
      spec:
        containers:
          - command:
              - /run.sh
            resources:
              limits:
                cpu: 0.4
                memory: 3Gi
              requests:
                cpu: 0.4
                memory: 3Gi
            env:
              - name: MAX_HEAP_SIZE
                value: 2G
              - name: HEAP_NEWSIZE
                value: 512M
              - name: POD_NAMESPACE
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.namespace
              - name: POD_IP
                valueFrom:
                  fieldRef:
                    fieldPath: status.podIP
            image: 172.30.1.1:5000/waus-bikeshedders/openshift-cassandra:latest
            name: cassandra-3
            ports:
              - containerPort: 9042
                name: cql
              - containerPort: 9160
                name: thrift
            volumeMounts:
              - mountPath: /cassandra_data
                name: cassandra-data
        volumes:
         - name: cassandra-data
           persistentVolumeClaim:
             claimName: cassandra-pvc-3
